spring.application.name=fitness-app
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=fitness
spring.rabbitmq.password=fitness
