CREATE TABLE exercise_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    exercise_id BIGINT NOT NULL,
    workout_id BIGINT NOT NULL,

    CONSTRAINT fk_exercise_plan_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercise(id),

    CONSTRAINT fk_exercise_plan_workout
        FOREIGN KEY (workout_id)
        REFERENCES workout(id)
);
