CREATE TABLE exercise_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reps INTEGER NOT NULL,
    weight DOUBLE PRECISION NOT NULL,

    exercise_plan_id BIGINT NOT NULL,

    CONSTRAINT fk_exercise_set_exercise_plan
        FOREIGN KEY (exercise_plan_id)
        REFERENCES exercise_plan(id)
        ON DELETE CASCADE
);
