CREATE TABLE workout_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workout_id BIGINT NOT NULL,

    workout_date_id BIGINT UNIQUE,

    CONSTRAINT fk_workout_plan_workout
        FOREIGN KEY (workout_id)
        REFERENCES workout(id),

    CONSTRAINT fk_workout_plan_workout_date
        FOREIGN KEY (workout_date_id)
        REFERENCES workout_date(id)
);
