CREATE TABLE schedule_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workout_date_id BIGINT NOT NULL,

    week_day INTEGER NOT NULL,

    date_time TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_schedule_entry_workout_date
        FOREIGN KEY (workout_date_id)
        REFERENCES workout_date(id)
        ON DELETE CASCADE
);
